update

diff --git a/.github/workflows/custom_build.yml b/.github/workflows/custom_build.yml
--- a/.github/workflows/custom_build.yml
+++ b/.github/workflows/custom_build.yml
@@ -1,5 +1,5 @@
 name: Custom Build
-run-name: WSA ${{ inputs.release_type }} Channel with ${{ inputs.root_sol }} and ${{ inputs.gapps_brand }}
+run-name: WSA ${{ inputs.release_type }} ${{ inputs.arch }} with ${{ inputs.root_sol }} and ${{ inputs.gapps_brand }} as ${{ inputs.custom_model }}
 on:
   workflow_dispatch:
     inputs:
@@ -8,65 +8,56 @@ on:
         description: Target CPU architecture of WSA.
         required: true
         options: [x64, arm64, Both]
-        default: Both
+        default: x64
       release_type:
         type: choice
         description: WSA Release Channel
         required: true
-        options: ["Retail","Release Preview","Insider Slow","Insider Fast"]
+        options: ["Retail","Release Preview","Insider Slow","Insider Fast","Insider Private"]
         default: "Retail"
+      user_code:
+        type: string
+        description: User code for WSA Insider User (Optional)
+        required: false
+        default: ""
       root_sol:
         type: choice
         description: Root solution
         required: true
-        options: ["Non-root","KernelSU","Magisk Delta (HuskyDG)","Magisk Stable","Magisk Beta","Magisk Canary","Magisk Debug"]
+        options: ["Non-root","KernelSU","Magisk Stable","Magisk Beta","Magisk Canary","Magisk Debug","Magisk Alpha (vvb2060)","Magisk Delta (HuskyDG)"]
         default: "Magisk Stable"
       gapps_brand:
         type: choice
         description: Google Apps brand
         required: true
-        options: ["OpenGApps v11.0","MindTheGapps v13.0","No GApps"]
+        options: ["MindTheGapps v13.0","No GApps"]
         default: "MindTheGapps v13.0"
-      gapps_var:
+      custom_model:
         type: choice
-        description: Google Apps variant.
+        description: Custom model
         required: true
-        options: ["Super","Stock","Full","Mini","Micro","Nano","Pico","TVStock","TVMini"]
-        default: "Pico"
+        options: ["WSA Default", "Pixel 4a", "Pixel 4a (5G)", "Pixel 5", "Pixel 5a", "Pixel 6", "Pixel 6 Pro", "Pixel 6a", "Pixel 7", "Pixel 7 Pro"]
+        default: "Pixel 5"
       compression:
         type: choice
         description: Compression format.
         required: true
-        options: [".zip",".7z",".xz"]
-        default: ".7z"
+        options: [".zip",".7z",".tar.xz"]
+        default: ".zip"
       remove_amazon:
-        description: "Remove Amazon AppStore from the system"
+        description: "Remove Amazon Appstore from the system"
         required: true
         default: true
         type: boolean
-      tag:
-        description: "Release Tag Name"
-        required: true
-        default: "WSA"
-        type: string
-      prerelease:
-        description: "Release as Prerelease"
-        required: false
-        default: false
-        type: boolean
-
-permissions:
-    contents: write
 
 jobs:
   matrix:
+    if: github.event.repository.fork == false
     runs-on: ubuntu-latest
     outputs:
       matrix: ${{ steps.set-matrix.outputs.matrix }}
     steps:
-      - name: Checkout
-        uses: actions/checkout@v3
-      - name: Generate build matrix
+      - name: Generate build matrix ⌛
         id: set-matrix
         uses: actions/github-script@v6
         with:
@@ -94,18 +85,65 @@ jobs:
     steps:
       - name: Checkout ♻️
         uses: actions/checkout@v3
-      - name: Install Dependencies 🧑‍🏭
+
+      - name: Get WSA Insider Preview build 🏭
+        if: inputs.release_type == 'Insider Private'
+        shell: python
         run: |
-          sudo apt-get update -y
-          sudo apt-get install -y lzip patchelf e2fsprogs python3 python3-pip aria2 p7zip-full attr unzip whiptail xz-utils qemu-utils
-          python3 -m pip install -r scripts/requirements.txt -q
-      - name: Grant exec permission to script 👑
-        run: chmod +x ./scripts/build.sh
+          import requests
+          import os
+          import json
+          import sys
+          env_file = os.getenv('GITHUB_ENV')
+          res = json.loads(requests.get(f"https://api.github.com/repos/YT-Advanced/WSAPackage/releases/latest").content)['assets']
+          for str in res:
+              with open(env_file, "a") as wr:
+                  wr.write("LINK=" + str['browser_download_url'])
+
+      - name: Setup Python 👷
+        uses: actions/setup-python@v4
+        with:
+          check-latest: true
+          python-version: '3.x'
+          cache: 'pip'
+          cache-dependency-path: scripts/
+
+      - name: Setup Python3 Virtual Enviroment 🐍
+        working-directory: scripts
+        run: |
+          sudo apt-get update
+          PYTHON_VENV_DIR="$(dirname "$PWD")/python3-env"
+          python3 -m venv "$PYTHON_VENV_DIR" || abort "Failed to create python3 virtual env"
+          # shellcheck disable=SC1091
+          source "$PYTHON_VENV_DIR/bin/activate" || abort "Failed to activate python3 virtual env"
+          python3 -c "import pkg_resources; pkg_resources.require(open('requirements.txt',mode='r'))" &>/dev/null || {
+              echo "Installing Python3 dependencies"
+              python3 -m pip install --upgrade -r requirements.txt || abort "Failed to install python3 dependencies"
+          }
+          deactivate
+
+      - name: Install Ubuntu Dependencies 🧑‍🏭
+        uses: awalsh128/cache-apt-pkgs-action@latest
+        with:
+          packages: ca-certificates patchelf e2fsprogs aria2 p7zip-full attr unzip xz-utils qemu-utils python3-venv
+          version: 1.0
+
+      - name: Download WSA Preview build + UI XAML manually 🧙🏻‍♂️
+        if: inputs.release_type == 'Insider Private'
+        run: |
+          wget -P ./download/wsa ${{ env.LINK }}
+          mv ./download/wsa/*.Msixbundle ./download/wsa-WIF.zip
+          rm -rf ./download/wsa
+          wget -P ./download/xaml https://globalcdn.nuget.org/packages/microsoft.ui.xaml.2.8.4.nupkg
+          7z x ./download/xaml/*.nupkg -o./download/xaml/
+          mv ./download/xaml/tools/AppX/${{ inputs.arch }}/Release/*.appx ./download/Microsoft.UI.Xaml.2.8_${{ inputs.arch }}.appx
+          rm -rf ./download/xaml
 
       - name: Build WSA 🏗️
         id: wsa
         run: |
-          declare -A opts=( ["RELEASE_TYPE,Retail"]="retail" ["RELEASE_TYPE,Release Preview"]="RP" ["RELEASE_TYPE,Insider Slow"]="WIS" ["RELEASE_TYPE,Insider Fast"]="WIF" ["ROOT_SOL,Magisk Stable"]="stable" ["ROOT_SOL,Magisk Beta"]="beta" ["ROOT_SOL,Magisk Canary"]="canary" ["ROOT_SOL,Magisk Debug"]="debug" ["ROOT_SOL,Magisk Delta (HuskyDG)"]="delta" ["ROOT_SOL,KernelSU"]="kernelsu" ["ROOT_SOL,Non-root"]="none" ["GAPPS_BRAND,OpenGApps v11.0"]="OpenGApps" ["GAPPS_BRAND,MindTheGapps v13.0"]="MindTheGapps" ["GAPPS_BRAND,No GApps"]="none" ["GAPPS_VAR,Pico"]="pico" ["GAPPS_VAR,Nano"]="nano" ["GAPPS_VAR,Micro"]="micro" ["GAPPS_VAR,Mini"]="mini" ["GAPPS_VAR,Full"]="full" ["GAPPS_VAR,Stock"]="stock" ["GAPPS_VAR,Super"]="super" ["GAPPS_VAR,TVStock"]="tvstock" ["GAPPS_VAR,TVMini"]="tvmini" ["REMOVE_AMAZON,true"]="--remove-amazon" ["COMPRESSION,.zip"]="zip" ["COMPRESSION,.7z"]="7z" ["COMPRESSION,.xz"]="xz" )
+          declare -A opts=( ["RELEASE_TYPE,Retail"]="retail" ["RELEASE_TYPE,Release Preview"]="RP" ["RELEASE_TYPE,Insider Slow"]="WIS" ["RELEASE_TYPE,Insider Fast"]="WIF"  ["ROOT_SOL,Magisk Stable"]="stable" ["ROOT_SOL,Magisk Beta"]="beta" ["ROOT_SOL,Magisk Canary"]="canary" ["ROOT_SOL,Magisk Debug"]="debug" ["ROOT_SOL,Magisk Delta (HuskyDG)"]="delta" ["ROOT_SOL,Magisk Alpha (vvb2060)"]="alpha" ["ROOT_SOL,KernelSU"]="kernelsu" ["ROOT_SOL,Non-root"]="none" ["GAPPS_BRAND,MindTheGapps v13.0"]="MindTheGapps" ["GAPPS_BRAND,No GApps"]="none" ["CUSTOM_MODEL,WSA Default"]="none" ["CUSTOM_MODEL,Pixel 4a"]="sunfish" ["CUSTOM_MODEL,Pixel 4a (5G)"]="bramble" ["CUSTOM_MODEL,Pixel 5"]="redfin" ["CUSTOM_MODEL,Pixel 5a"]="barbet" ["CUSTOM_MODEL,Pixel 6 Pro"]="raven" ["CUSTOM_MODEL,Pixel 6"]="oriole" ["CUSTOM_MODEL,Pixel 6a"]="bluejay" ["CUSTOM_MODEL,Pixel 7"]="panther" ["CUSTOM_MODEL,Pixel 7 Pro"]="cheetah" ["REMOVE_AMAZON,true"]="--remove-amazon" ["COMPRESSION,.zip"]="zip" ["COMPRESSION,.7z"]="7z" ["COMPRESSION,.tar.xz"]="xz" )
+
           if [[ "${{ inputs.root_sol }}" == *Magisk* ]]; then
               MAGISK_VER="${opts[ROOT_SOL,${{ inputs.root_sol }}]}"
               ROOT_SOL="magisk"
@@ -113,21 +151,24 @@ jobs:
               ROOT_SOL="${opts[ROOT_SOL,${{ inputs.root_sol }}]}"
               MAGISK_VER="${opts[ROOT_SOL,Magisk Stable]}"
           fi
-          
-          ./scripts/build.sh --arch ${{ matrix.arch }} --release-type ${opts[RELEASE_TYPE,${{ inputs.release_type }}]} --magisk-ver $MAGISK_VER --gapps-brand ${opts[GAPPS_BRAND,${{ inputs.gapps_brand }}]} --gapps-variant ${opts[GAPPS_VAR,${{ inputs.gapps_var }}]} --root-sol $ROOT_SOL --compress-format ${opts[COMPRESSION,${{ inputs.compression }}]} ${opts[REMOVE_AMAZON,${{ inputs.remove_amazon }}]}
+
+          mkdir -p download
+          echo -e "user_code=$(cat $GITHUB_EVENT_PATH | jq -r '.inputs.user_code')" > download/.ms_account
+
+          if [[ "${{ inputs.release_type }}" == *Private* ]]; then
+              ./scripts/build.sh --arch ${{ matrix.arch }} --release-type WIF --magisk-ver $MAGISK_VER --gapps-brand ${opts[GAPPS_BRAND,${{ inputs.gapps_brand }}]} --custom-model ${opts[CUSTOM_MODEL,${{ inputs.custom_model }}]} --skip-download-wsa --root-sol $ROOT_SOL --compress-format ${opts[COMPRESSION,${{ inputs.compression }}]} ${opts[REMOVE_AMAZON,${{ inputs.remove_amazon }}]}
+          else
+              ./scripts/build.sh --arch ${{ matrix.arch }} --release-type ${opts[RELEASE_TYPE,${{ inputs.release_type }}]} --magisk-ver $MAGISK_VER --gapps-brand ${opts[GAPPS_BRAND,${{ inputs.gapps_brand }}]} --custom-model ${opts[CUSTOM_MODEL,${{ inputs.custom_model }}]} --root-sol $ROOT_SOL --compress-format ${opts[COMPRESSION,${{ inputs.compression }}]} ${opts[REMOVE_AMAZON,${{ inputs.remove_amazon }}]}
+          fi
+
       - name: File Checksum ✔️
+        if: inputs.compression != '.zip'
+        working-directory: output
         run: |
-          cd ./output/
           sha256sum '${{ steps.wsa.outputs.artifact }}${{ inputs.compression }}' >> sha256-checksum.txt
-#      - name: Upload Artifact 🤌
-#        uses: actions/upload-artifact@v3
-#        with:
-#          name: ${{ steps.wsa.outputs.artifact }}
-#          path: ./output
-      - name: Upload Asset
-        uses: softprops/action-gh-release@v1
+
+      - name: Upload Artifact 📦
+        uses: actions/upload-artifact@v3
         with:
-            files: ./output/${{ steps.wsa.outputs.artifact }}.*
-            name: WSA
-            tag_name: ${{ inputs.tag }}
-            prerelease: ${{ inputs.prerelease }}
+          name: ${{ steps.wsa.outputs.artifact }}
+          path: output
